version: '3'

services:
  game-server:
    image: llmctf/2024f-rev-shuffle
    networks:
      ctfnet:
        aliases:
          - rev.chal.csaw.io
    ports:
      - 9999:9999

networks:
  ctfnet:
    external: true