services:
  game-server:
    image: llmctf/2024f-msc-boss_battle
    networks:
      ctfnet:
        aliases:
          - misc.chal.csaw.io
    environment:
      PORT: "31137"
      HTTP_PORT: "8545"
      FLAG: "flag{not_the_flag}"
      PUBLIC_IP: "127.0.0.1"
      SHARED_SECRET: "some_shared_secret_here"
    ports:
      - "31137:31137"
      - "8545:8545"

networks:
  ctfnet:
    external: true